######################################################################
# Automatically generated by qmake (3.0) Sun Sep 8 23:26:34 2019
######################################################################

TEMPLATE = app
TARGET = led_switch
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
